# Generated by Django 2.1.1 on 2018-10-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('device', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(max_length=128)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.IntegerField(choices=[(1, '42区'), (2, '段子'), (3, '图片'), (4, '挨踢1024')])),
                ('favor_count', models.CharField(default=0, max_length=64)),
                ('comment_count', models.CharField(default=0, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('last_time', models.DateTimeField()),
                ('times', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('user', 'email')},
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui', to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
